name: WMR Build & Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'
      - name: Merge master -> gh-pages
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: yarn --version
      - run: yarn install
      - run: yarn build --out docs
        env:
          CI: true
      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          author_name: Egor Laufer
          author_email: laufer@hey.com
          branch: gh-pages
          pull_strategy: '--autostash'
          message: Deploy to gh pages
          add: 'docs/ --force'
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
